### ISSUE TITLE
WSREP: access file(/var/lib/mysql//gvwstate.dat) failed(No such file or directory)

### ISSUE THREAD

**Issue by govindinfi** [codership/wsrep-API#68]
### I am facing below issue on mariadb galera cluster. nodes getting unsynchronized very frequently. every day i am facing sync issue on every node. Please help.

- Mariadb verison 10.5.X
- Galera verison 26.4.11

# WSREP: access file(/var/lib/mysql//gvwstate.dat) failed(No such file or directory)

![image](https://user-images.githubusercontent.com/102216439/216057365-40740bd5-6a65-4693-ace8-51da86b2c948.png)

**Comment by ayurchen** [comment]
This in particular is not an issue, you have another problem that causes nodes desynchronization. This file is important only when recovering from total blackout. Look for errors, not warnings.

**Comment by govindinfi** [comment]
Thanks for your response.

Please solve the nodes desynchronizations issue on priority.

--
Regards,
***@***.***
Govind Kumar
Senior System Admin
Mob: +91 9811810427<tel:+919811810427>
E-mail: ***@***.******@***.***>
Website: www.infinitylabs.in<http://www.infinitylabs.in/>

**Comment by govindinfi** [comment]
As checked, there is no error found like with nodes. but nodes going non-primary.
